name: Release Container to Docker Hub

on:
  push:
    branches:
      # ^(master|alpha|beta|release|[0-9]+\.x$|[0-9]+\.x\.x$|[0-9]+\.[0-9]+\.x)$
      - master
      - alpha
      - beta
      - release
      - '[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.[0-9]+.x'

jobs:
  build-and-release:
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node: ['12']

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v1.1.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install

      - name: Checks
        run: yarn run check

      - name: Unit Tests
        run: yarn run test --passWithNoTests --coverage

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: yarn release
